// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj45Cv5LA4HH5AEVHDhEK4ui0uLUQHdTI',
    appId: '1:529620963497:web:1b263842b15fa221b6d9b8',
    messagingSenderId: '529620963497',
    projectId: 'grameen-gadget',
    authDomain: 'grameen-gadget.firebaseapp.com',
    storageBucket: 'grameen-gadget.firebasestorage.app',
    measurementId: 'G-TVXVNX99MN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJgdpRnNZ2N5v_4k-tUyi2pdKzyldOYC4',
    appId: '1:529620963497:android:40b76f24e840d326b6d9b8',
    messagingSenderId: '529620963497',
    projectId: 'grameen-gadget',
    storageBucket: 'grameen-gadget.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlL4Bscr6EyqQaRZYWT6VD_nnXVnyeu3E',
    appId: '1:529620963497:ios:b822799ce1d91a63b6d9b8',
    messagingSenderId: '529620963497',
    projectId: 'grameen-gadget',
    storageBucket: 'grameen-gadget.firebasestorage.app',
    iosBundleId: 'com.example.kghAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlL4Bscr6EyqQaRZYWT6VD_nnXVnyeu3E',
    appId: '1:529620963497:ios:b822799ce1d91a63b6d9b8',
    messagingSenderId: '529620963497',
    projectId: 'grameen-gadget',
    storageBucket: 'grameen-gadget.firebasestorage.app',
    iosBundleId: 'com.example.kghAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj45Cv5LA4HH5AEVHDhEK4ui0uLUQHdTI',
    appId: '1:529620963497:web:6ab7138d36e4114ab6d9b8',
    messagingSenderId: '529620963497',
    projectId: 'grameen-gadget',
    authDomain: 'grameen-gadget.firebaseapp.com',
    storageBucket: 'grameen-gadget.firebasestorage.app',
    measurementId: 'G-1L49RPGBV4',
  );
}
